version: '3'
services:
  app:
    image: postgres:15.4
    container_name: postgres_db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: root

    volumes:
      - ./Create_tables.sql:/docker-entrypoint-initdb.d/Create_tables.sql